name: Build NixOS Configs

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build laptop config (black)
        run: nix build .#nixosConfigurations.black.config.system.build.toplevel

      - name: Build pc config (white)
        run: nix build .#nixosConfigurations.white.config.system.build.toplevel
